# Generated by Django 5.1.1 on 2024-09-14 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderproduct_quantity"),
        ("products", "0002_product_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
