# Generated by Django 5.1.1 on 2024-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="fecha de creacion"
            ),
        ),
    ]
